CREATE TABLE USUARIO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100)
)

CREATE TABLE PEDIDO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMEPRODUTO VARCHAR(100),
	USUARIOID INT,
	FOREIGN KEY (USUARIOID) REFERENCES USUARIO(ID)
)